### ISSUE TITLE
fresh install

### ISSUE THREAD

**Issue by 0b11001111** [pymontecarlo/pymontecarlo#56] opened 2018-02-10 19:45 UTC
In order to install the latest version pymontecarlo on @silrichter's machine I decided to make a test setup first using Wndows 7 and Fedora 27 in VMs. I followed the [tutorial](https://github.com/pymontecarlo/pymontecarlo/blob/master/docs/installation.rst) and used the latest copies of *pymontecarlo*, *pymontecarlo-casino2* and *pyxray*. While *pymontecarlo*'s tests succeed *pymontecarlo-casino* fails. The output can be found in the attachment.

Am I missing anything? On my machine anything works just fine but I also have kind of a messed up setup.

[pymontecarlo_casino2_nosetest.txt](https://github.com/pymontecarlo/pymontecarlo/files/1713715/pymontecarlo_casino2_nosetest.txt)

**Comment by ppinard** [comment] 2018-02-11 09:49
You use the git repositories or the PyPI packages? The PyPI packages are not updated so I don't know if they still work. For the git repositories, did you have Git LFS installed?

**Comment by 0b11001111** [comment] 2018-02-11 10:44
I use the git repositories and I installed Git LFS before setting up everything.

**Comment by ppinard** [comment] 2018-02-11 12:06
Are the MD5 checksum matching these?

```
7011133fe3c6364e8063cf56373527f1  HorizontalLayers10.sim
d83592a001d6f468309fabe3cddf6dff  HorizontalLayers11.sim
e9af38de0f9022357c5441b7bd8a3658  HorizontalLayers2.sim
ea8158d6905b6901c860c4b7d21241b8  HorizontalLayers3.sim
d028416e8923ea2eedff9f7d40d0cc6c  HorizontalLayers4.sim
3d4418c4906e2d6799c13d370725668d  HorizontalLayers5.sim
d2d661a8e11c9333790fccf70f8b0060  HorizontalLayers6.sim
0e78b64dd8dd0d5792233d3aaf66f914  HorizontalLayers7.sim
de0030ba00f71166dccc93369c14f0b5  HorizontalLayers8.sim
21cf6f9aa93a3cb603215aad9009d351  HorizontalLayers9.sim
fdb922d90bc469000370ac7e2745c11e  Substrate.sim
515db69fa951ce55b9a1ffa65c121b7b  VerticalLayers10.sim
2542ef7f4a6cb437ecf9e134e136c237  VerticalLayers11.sim
401dcc9d4af34d5223371b4bf3fed3ae  VerticalLayers2.sim
eccfeb918a778bcf58ee30742188f42a  VerticalLayers3.sim
8c4914abc3c3e41be5fc092de2dda4da  VerticalLayers4.sim
443f5462d064690e2ee3d38d51e49ef5  VerticalLayers5.sim
238fed1c1470380fccd179b8ad3489e6  VerticalLayers6.sim
277f1208bdb3869cac39bcb612067d65  VerticalLayers7.sim
927df8beca035fcff18a9208149ca6de  VerticalLayers8.sim
5a30d87ae10dcbf3de581a71f481ecf6  VerticalLayers9.sim
```

**Comment by 0b11001111** [comment] 2018-02-12 14:51
They weren’t and I figured out that git-lfs' installation script failed at some point. I installed the git-lfs package from fedora repositories directly and it worked like a charm.

What about establishing a troubleshooting section in the docs? There was no hint at installation that I had a incomplete repository so other people may also run in this issue. I can also think of automating this by `setup.py` checking git-lfs controlled files by checking if they have a plausible size or the right checksum directly. What do you think?

**Comment by ppinard** [comment] 2018-02-12 22:23
I would avoid putting any check in `setup.py` since `setup.py` is also used to install `pymontecarlo-casino2` as a binary package (i.e. wheel). The Git LFS problem is only for developers. 

I think the problem is that some `.sim` files were already committed before I switched to LFS. These are the files you get when Git LFS is not installed. I now have manually removed this files and readded the `.sim` with LFS. I think this will solve the problem. If Git LFS is not installed, the exporter will raise an `IOError`.

**Comment by ppinard** [comment] 2018-09-15 16:22
@luoc0815 can I close this issue?

**Closed as completed** 2018-09-18 13:05 UTC
